name: ubuntu-per-arch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7, aarch64, riscv64, ppc64le]
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v3
        name: "Build"
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          githubToken: ${{ github.token }}
          distro: ubuntu22.04
          install: |
            sudo apt-get update
            sudo apt-get install -y build-essential
          run: |
            cmake --workflow release
