name: x86-windows-mingw

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        choco install mingw --version=8.1.0 -y --force
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" >> $env:GITHUB_PATH

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure
      run: cmake --preset release -G "MinGW Makefiles"

    - name: Build
      run: cmake --build --preset release
