name: x86_64-windows-clang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: egor-tensin/setup-clang@v1
        with:
          platform: x64

      - name: Configure
        run: cmake --preset release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset release
