name: x86_64-macos-clang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Build"
    runs-on: "macos-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset release
