name: x86_64-windows-clang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM (Clang)
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      - name: Configure
        run: cmake --preset release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build --preset release
